# Generated by Django 3.0.5 on 2020-07-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='fullname',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='profile_pic',
            new_name='pic',
        ),
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(default='slug'),
            preserve_default=False,
        ),
    ]
